# Built with Jekyll 3.2.0

# Setup
title:               2nd U.S. Semantic Technologies Symposium 2019
tagline:             ''
description:         ''
url:                 'http://us2ts.github.io'
baseurl:             ''

# About/contact
author:
  name:              Maulik R. Kamdar
  url:               https://twitter.com/maulikkamdar
  email:             maulikrk@stanford.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: orange

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

gems:
  - jekyll-last-modified-at


# Theme
#theme: "ed."
